# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3
vars:
  root: { sh: git rev-parse --show-toplevel }
  temp_dir: "{{ .root }}/.tmp"
  measurements: "{{ .root }}/1brc/measurements.txt"

tasks:
  calculate-baseline:
    status: ["test -f {{ .root }}/.baseline"]
    dir: "{{ .root }}/1brc"
    cmds:
      - ./calculate_average_baseline.sh > {{ .root }}/.baseline

  measure:
    label: measure-{{ .name }}
    deps: [calculate-baseline]
    preconditions:
      - test ! -z "{{ .name }}"
    cmds:
      - mkdir -p {{ .temp_dir }}
      - go build -C {{ .name }} -o {{ .temp_dir }}/{{ .name }} .
      - "{{ .temp_dir }}/{{ .name }} -measurements {{ .measurements }} > {{ .temp_dir }}/{{ .name }}-result"
      - cmp .baseline {{ .temp_dir }}/{{ .name }}-result
